on:
  push:
    branches: [ main ]
jobs:
  build_and_push:
    name: Push docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Write .env file
        run: |
          touch ./.env
          echo "${{ secrets.ENV }}" >> ./.env

      - name: Build and Push to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          docker build -t ${{ secrets.DOCKERHUB_REGISTRY_URL }}:backend .
          docker push ${{ secrets.DOCKERHUB_REGISTRY_URL }}:backend

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     ecr: auto
      #     logout: true
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # - name: Extract metadata (labels, tags, etc.) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v5

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_REGISTRY_URL }}:backend
      #     labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.BASTION_HOST }}
          username: ${{ secrets.BASTION_USER }}
          key: ${{ secrets.KEY }}
          script: |
            ssh -i ${{ secrets.PEM_PATH }} ubuntu@${{ secrets.PRIVATE_EC2_IP }} << 'EOF'
              sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
              sudo docker pull ${{ secrets.DOCKERHUB_REGISTRY_URL }}:backend
              sudo docker run -p 8000:8000 ${{ secrets.DOCKERHUB_REGISTRY_URL }}:backend
              sudo docker image prune -f
            EOF
