on:
  push:
    branches: [ main ]
jobs:
  build_and_push:
    name: Push docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Touch .env
        run: |
          touch ./.env
          echo ${{ secrets.ENV }} >> ./.env
        shell: bash

      - name: Build and Push to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          docker build -t ${{ secrets.DOCKERHUB_REGISTRY_URL }}:backend .
          docker push ${{ secrets.DOCKERHUB_REGISTRY_URL }}:backend

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.BASTION_HOST }}
          username: ${{ secrets.BASTION_USER }}
          key: ${{ secrets.KEY }}
          script: |
            ssh -i ${{ secrets.PEM_PATH }} ubuntu@${{ secrets.PRIVATE_EC2_IP }} << 'EOF'
              sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
              sudo docker stop backend
              sudo docker pull ${{ secrets.DOCKERHUB_REGISTRY_URL }}:backend
              sudo docker run -d -p 8000:8000 --rm --name backend ${{ secrets.DOCKERHUB_REGISTRY_URL }}:backend
              sudo docker image prune -f
            EOF
